train_gpu_config:
  use_gpu: True
  gpu_enum:
    - gpu_enum: 0
    - gpu_enum: 1



test_gpu_config:
  use_cuda: False
  gpu_enum:
    - gpu_enum: 0

train_parameter:
  format_list:
    - format_list: jpg
    - format_list: png
    - format_list: jpeg
    - format_list: JPG
    - format_list: PNG

  pretrained: False
  model_name: resnet50
  img_size: 512
  epoch: 100
  embedding: 512
  batch_size: 12
  data_shuffle: True
  learning_rate: 0.001
  valid_iter_num: 500
  val_interval_step: 3000
  data_loader_works: 16
  image_gray_scale: True
  scale_resize_pad: True

path_config:
  train_data_path: /data/User/hanati/image_critic_dataset/triplet_data
  valid_data_path: /data/User/hanati/image_critic_dataset/triplet_data
  model_save_path: weights/triplet
  pretrained_model: weights/resnet50-19c8e357.pth